services:

  webui:
    container_name: ${NAMESPACE}_webui
    image: ghcr.io/open-webui/open-webui:latest-cuda
    pull_policy: always
    tty: true
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL}'
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: 1
              capabilities:
                - gpu

  ollama:
    container_name: ${NAMESPACE}_ollama
    image: ollama/ollama:latest
    pull_policy: always
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    tty: true
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: 1
              capabilities:
                - gpu

  python:
    #build:
    #  context: .docker/python
    #  args:
    #    PY_VERSION: ${PY_VERSION}
    container_name: ${NAMESPACE}_python
    depends_on:
      - ollama
    image: osioaliu/python:${PY_VERSION}
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'TZ=${TZ}'
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL}'
    working_dir: /usr/src/
    volumes:
      - ./src:/usr/src
    command: >
      bash -c "if [ -f 'requirements.txt' ]; then
        pip install --root-user-action=ignore -r requirements.txt;
      fi;
      tail -f /dev/null
      "

volumes:
  webui:
  ollama:

networks:
  default:
    driver: bridge